fix: token github

diff --git a/.github/workflows/tag-on-release.yml b/.github/workflows/tag-on-release.yml
--- a/.github/workflows/tag-on-release.yml
+++ b/.github/workflows/tag-on-release.yml
@@ -1,64 +1,54 @@
 name: Tag on Release PR
 
 on:
-  pull_request:
-    branches:
-      - 'release/**'
-    types: [opened, synchronize, reopened]
-  push:
-    tags:
-      - '**'
+    pull_request:
+        branches:
+            - 'release/**'
+        types: [opened, synchronize, reopened]
+    push:
+        tags:
+            - '**'
 
 jobs:
-  validate-tag-in-pr:
-    runs-on: ubuntu-latest
+    validate-tag-in-pr:
+        runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0  # Esto es importante para obtener todo el historial
+        steps:
+            - name: Checkout repository
+              uses: actions/checkout@v3
+              with:
+                  fetch-depth: 0 # This is important to get all history for the tag check
 
-      - name: Check for tag in PR commits
-        id: check_tag
-        run: |
-          # Obtener la lista de commits en el PR
-          PR_COMMITS=$(git log --format=%H origin/${{ github.base_ref }}..origin/${{ github.head_ref }})
-          
-          # Inicializar una variable para rastrear si se encontró un tag
-          TAG_FOUND=false
-          
-          # Iterar sobre cada commit en el PR
-          for COMMIT in $PR_COMMITS
-          do
-            # Verificar si este commit tiene un tag
-            TAG=$(git tag --contains $COMMIT)
-            if [ ! -z "$TAG" ]; then
-              echo "Tag encontrado: $TAG en el commit $COMMIT"
-              TAG_FOUND=true
-              break
-            fi
-          done
-          
-          # Verificar si se encontró algún tag
-          if [ "$TAG_FOUND" = false ]; then
-            echo "No se encontró ningún tag en los commits del PR"
-            exit 1
-          else
-            echo "Se encontró al menos un tag en los commits del PR"
-          fi
+            - name: Check for tag in PR commits
+              id: check_tag
+              run: |
+                  # Get PR list
+                  PR_COMMITS=$(git log --format=%H origin/${{ github.base_ref }}..origin/${{ github.head_ref }})
 
-          - name: Install GitHub CLI
-          run: sudo apt-get install gh -y
-  
-      - name: Authenticate GitHub CLI
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: gh auth login --with-token
-  
-      - name: Comment on PR
-        if: failure()
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          gh pr comment ${{ github.event.pull_request.number }} --body "No se encontró ningún tag en los commits de este PR. Por favor, asegúrate de agregar un tag antes de fusionar."
+                  TAG_FOUND=false
+
+                  for COMMIT in $PR_COMMITS
+                  do
+                    # Verify tag in commit
+                    TAG=$(git tag --contains $COMMIT)
+                    if [ ! -z "$TAG" ]; then
+                      echo "Tag finded: $TAG in commit $COMMIT"
+                      TAG_FOUND=true
+                      break
+                    fi
+                  done
+
+                  if [ "$TAG_FOUND" = false ]; then
+                    echo "Not found tag in this project"
+                    exit 1
+                  else
+                    echo "Tags is provided"
+                  fi
+            - name: Add comment
+              run: gh pr comment "$PRNUMBER" --body "$BODY"
+              env:
+                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+                  GH_REPO: ${{ github.repository }}
+                  PRNUMBER: ${{ github.event.pull_request.number }}
+                  BODY: >
+                      No se encontró ningún tag en los commits de este PR. Por favor, asegúrate de agregar un tag antes de fusionar.
